# .github/workflows/deploy.yml
name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Triggers on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js 20 or your preferred version

      # Step 3: Verify Node.js Version (optional)
      - name: Verify Node.js Version
        run: node -v

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 5: Build React Application
      - name: Build React Application
        run: npm run build

      # Step 6: Deploy to S3
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          AWS_BUCKET_NAME: rohithkankipati.com
        run: |
          npm install -g aws-cli
          aws s3 sync ./build/ s3://$AWS_BUCKET_NAME --region $AWS_REGION --delete
